### PR TITLE
changelog for 0.1.2

### PR DESCRIPTION
**Pull request by kbrock**

### CODE REVIEW

**Comment by Fryguy** [comment]
typo in the branch / commit title / PR title - the actual version is 0.1.2

**Comment by kbrock** [comment]
updated commit and title.

Do you want me to rename the branch and open a new pr?

**Comment by Fryguy** [comment]
I can change the branch name when I merge the commit, so it's not a big deal.

**Comment by Fryguy** [comment]
```
Merge pull request #33 from kbrock/v0.1.2

changelog for 0.1.2
```

**Pull request merged**
