### PR TITLE
remove unused cache directory travis.yml option

### PR DESCRIPTION
**Pull request by d-m-u**
since we're not specifying directories to cache, we could one line this

### CODE REVIEW

**Review by kbrock — COMMENTED** [review]
works for me:

https://docs.travis-ci.com/user/caching/#bundler

the `sudo: false` does nothing
Also, what is the most recent dist for ~~bundler~~ travis?

seems if we are updating this, we may as well get rid of most of the cruft

**Comment by kbrock** [comment]
UPDATE: we are on the right version of travis.

only the sudo change

**Comment by Fryguy** [comment]
Gah sorry @kbrock I misread your comment as asking for an additional change.  As it stood, this PR was so simple I just merged it... sudo can be a follow up.

**Comment by d-m-u** [comment]
this _was_ the sudo change Keenan was referring to, so we're good here. thanks for the merge.

**Pull request merged**
